[build]
publish = "."
command = "npm install && npm run build"

[functions]
directory = "netlify/functions"
included_files = ["!node_modules/@netlify/**"]

[build.environment]
NODE_VERSION = "18"

[[redirects]]
  from = "/r/:code"
  to = "/.netlify/functions/redirect?code=:code"
  status = 200
